---
# Source: https://allen-ball.github.io/
url: >-
  https://blog.hcf.dev/

# Source: https://allen-ball.github.io/javadoc/
javadoc:
  url: >-
    https://blog.hcf.dev/javadoc

title: Allen D. Ball
description: >-
  A blog about Java and other stuff.

email: ball@hcf.dev
github_username: allen-ball

footer-links:
  email: ball@hcf.dev
  github: allen-ball/allen-ball
  linkedin: https://www.linkedin.com/in/allen-ball/
  stackoverflow: users/11866308/allen-d-ball

google_analytics: UA-137275928-1

theme: minima
show_excerpts: true

markdown: kramdown
kramdown:
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md
  - CNAME
